language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="nunchaku:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="nunchaku" OCAML_VERSION="4.02.3" EXTRA_DEPS="smbc"
  - PACKAGE="nunchaku" OCAML_VERSION="4.03" EXTRA_DEPS="smbc"
  - PACKAGE="nunchaku" OCAML_VERSION="4.04" EXTRA_DEPS="smbc"
  - PACKAGE="nunchaku" OCAML_VERSION="4.05" EXTRA_DEPS="smbc"
  - PACKAGE="nunchaku" OCAML_VERSION="4.06" EXTRA_DEPS="smbc"
  - PACKAGE="nunchaku" OCAML_VERSION="4.07" EXTRA_DEPS="smbc"
